/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAppointmentsRouteImport } from './routes/admin/appointments'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminCouponsRouteImport } from './routes/admin/coupons'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminEmployeesRouteImport } from './routes/admin/employees'
import { Route as AdminInvoicesRouteImport } from './routes/admin/invoices'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminPaywayRouteImport } from './routes/admin/payway'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminPurchaseOrdersRouteImport } from './routes/admin/purchase-orders'
import { Route as AdminRepairsRouteImport } from './routes/admin/repairs'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSuppliersRouteImport } from './routes/admin/suppliers'
import { Route as AdminTechniciansRouteImport } from './routes/admin/technicians'
import { Route as AdminWarrantyRouteImport } from './routes/admin/warranty'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSplatRouteImport } from './routes/dashboard/$'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard/invoices'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard/payments'
import { Route as DashboardRepairsRouteImport } from './routes/dashboard/repairs'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardSupportRouteImport } from './routes/dashboard/support'
import { Route as DashboardWarrantyRouteImport } from './routes/dashboard/warranty'
import { Route as DashboardWishlistRouteImport } from './routes/dashboard/wishlist'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as RepairsIndexRouteImport } from './routes/repairs/index'
import { Route as AdminInventoryIndexRouteImport } from './routes/admin/inventory/index'
import { Route as AdminInventoryLowStockRouteImport } from './routes/admin/inventory/low-stock'
import { Route as DashboardReceiptIdRouteImport } from './routes/dashboard/receipt.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/admin/appointments',
  path: '/admin/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/admin/coupons',
  path: '/admin/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/admin/invoices',
  path: '/admin/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaywayRoute = AdminPaywayRouteImport.update({
  id: '/admin/payway',
  path: '/admin/payway',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPurchaseOrdersRoute = AdminPurchaseOrdersRouteImport.update({
  id: '/admin/purchase-orders',
  path: '/admin/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRepairsRoute = AdminRepairsRouteImport.update({
  id: '/admin/repairs',
  path: '/admin/repairs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/admin/suppliers',
  path: '/admin/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTechniciansRoute = AdminTechniciansRouteImport.update({
  id: '/admin/technicians',
  path: '/admin/technicians',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWarrantyRoute = AdminWarrantyRouteImport.update({
  id: '/admin/warranty',
  path: '/admin/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSplatRoute = DashboardSplatRouteImport.update({
  id: '/dashboard/$',
  path: '/dashboard/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/dashboard/invoices',
  path: '/dashboard/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/dashboard/notifications',
  path: '/dashboard/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/dashboard/orders',
  path: '/dashboard/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/dashboard/payments',
  path: '/dashboard/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRepairsRoute = DashboardRepairsRouteImport.update({
  id: '/dashboard/repairs',
  path: '/dashboard/repairs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/dashboard/support',
  path: '/dashboard/support',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWarrantyRoute = DashboardWarrantyRouteImport.update({
  id: '/dashboard/warranty',
  path: '/dashboard/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWishlistRoute = DashboardWishlistRouteImport.update({
  id: '/dashboard/wishlist',
  path: '/dashboard/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairsIndexRoute = RepairsIndexRouteImport.update({
  id: '/repairs/',
  path: '/repairs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryIndexRoute = AdminInventoryIndexRouteImport.update({
  id: '/admin/inventory/',
  path: '/admin/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryLowStockRoute = AdminInventoryLowStockRouteImport.update({
  id: '/admin/inventory/low-stock',
  path: '/admin/inventory/low-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReceiptIdRoute = DashboardReceiptIdRouteImport.update({
  id: '/dashboard/receipt/$id',
  path: '/dashboard/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/stores': typeof StoresRoute
  '/wishlist': typeof WishlistRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payway': typeof AdminPaywayRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/repairs': typeof AdminRepairsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/admin/warranty': typeof AdminWarrantyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/$': typeof DashboardSplatRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/repairs': typeof DashboardRepairsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/warranty': typeof DashboardWarrantyRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/repairs/': typeof RepairsIndexRoute
  '/admin/inventory/low-stock': typeof AdminInventoryLowStockRoute
  '/dashboard/receipt/$id': typeof DashboardReceiptIdRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/stores': typeof StoresRoute
  '/wishlist': typeof WishlistRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payway': typeof AdminPaywayRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/repairs': typeof AdminRepairsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/admin/warranty': typeof AdminWarrantyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/$': typeof DashboardSplatRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/repairs': typeof DashboardRepairsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/warranty': typeof DashboardWarrantyRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/products': typeof ProductsIndexRoute
  '/repairs': typeof RepairsIndexRoute
  '/admin/inventory/low-stock': typeof AdminInventoryLowStockRoute
  '/dashboard/receipt/$id': typeof DashboardReceiptIdRoute
  '/admin/inventory': typeof AdminInventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/stores': typeof StoresRoute
  '/wishlist': typeof WishlistRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payway': typeof AdminPaywayRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/repairs': typeof AdminRepairsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/admin/warranty': typeof AdminWarrantyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/$': typeof DashboardSplatRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/repairs': typeof DashboardRepairsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/warranty': typeof DashboardWarrantyRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/repairs/': typeof RepairsIndexRoute
  '/admin/inventory/low-stock': typeof AdminInventoryLowStockRoute
  '/dashboard/receipt/$id': typeof DashboardReceiptIdRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/stores'
    | '/wishlist'
    | '/admin/$'
    | '/admin/analytics'
    | '/admin/appointments'
    | '/admin/audit-logs'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/invoices'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/payway'
    | '/admin/products'
    | '/admin/purchase-orders'
    | '/admin/repairs'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/suppliers'
    | '/admin/technicians'
    | '/admin/warranty'
    | '/blog/$slug'
    | '/dashboard/$'
    | '/dashboard/invoices'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/repairs'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/warranty'
    | '/dashboard/wishlist'
    | '/products/$productId'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/products/'
    | '/repairs/'
    | '/admin/inventory/low-stock'
    | '/dashboard/receipt/$id'
    | '/admin/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/stores'
    | '/wishlist'
    | '/admin/$'
    | '/admin/analytics'
    | '/admin/appointments'
    | '/admin/audit-logs'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/invoices'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/payway'
    | '/admin/products'
    | '/admin/purchase-orders'
    | '/admin/repairs'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/suppliers'
    | '/admin/technicians'
    | '/admin/warranty'
    | '/blog/$slug'
    | '/dashboard/$'
    | '/dashboard/invoices'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/repairs'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/warranty'
    | '/dashboard/wishlist'
    | '/products/$productId'
    | '/admin'
    | '/blog'
    | '/dashboard'
    | '/products'
    | '/repairs'
    | '/admin/inventory/low-stock'
    | '/dashboard/receipt/$id'
    | '/admin/inventory'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/stores'
    | '/wishlist'
    | '/admin/$'
    | '/admin/analytics'
    | '/admin/appointments'
    | '/admin/audit-logs'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/invoices'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/payway'
    | '/admin/products'
    | '/admin/purchase-orders'
    | '/admin/repairs'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/suppliers'
    | '/admin/technicians'
    | '/admin/warranty'
    | '/blog/$slug'
    | '/dashboard/$'
    | '/dashboard/invoices'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/repairs'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/warranty'
    | '/dashboard/wishlist'
    | '/products/$productId'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/products/'
    | '/repairs/'
    | '/admin/inventory/low-stock'
    | '/dashboard/receipt/$id'
    | '/admin/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  StoresRoute: typeof StoresRoute
  WishlistRoute: typeof WishlistRoute
  AdminSplatRoute: typeof AdminSplatRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPaywayRoute: typeof AdminPaywayRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminPurchaseOrdersRoute: typeof AdminPurchaseOrdersRoute
  AdminRepairsRoute: typeof AdminRepairsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminTechniciansRoute: typeof AdminTechniciansRoute
  AdminWarrantyRoute: typeof AdminWarrantyRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DashboardSplatRoute: typeof DashboardSplatRoute
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardRepairsRoute: typeof DashboardRepairsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardWarrantyRoute: typeof DashboardWarrantyRoute
  DashboardWishlistRoute: typeof DashboardWishlistRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  RepairsIndexRoute: typeof RepairsIndexRoute
  AdminInventoryLowStockRoute: typeof AdminInventoryLowStockRoute
  DashboardReceiptIdRoute: typeof DashboardReceiptIdRoute
  AdminInventoryIndexRoute: typeof AdminInventoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/admin/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payway': {
      id: '/admin/payway'
      path: '/admin/payway'
      fullPath: '/admin/payway'
      preLoaderRoute: typeof AdminPaywayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/purchase-orders': {
      id: '/admin/purchase-orders'
      path: '/admin/purchase-orders'
      fullPath: '/admin/purchase-orders'
      preLoaderRoute: typeof AdminPurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/repairs': {
      id: '/admin/repairs'
      path: '/admin/repairs'
      fullPath: '/admin/repairs'
      preLoaderRoute: typeof AdminRepairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/admin/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/technicians': {
      id: '/admin/technicians'
      path: '/admin/technicians'
      fullPath: '/admin/technicians'
      preLoaderRoute: typeof AdminTechniciansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/warranty': {
      id: '/admin/warranty'
      path: '/admin/warranty'
      fullPath: '/admin/warranty'
      preLoaderRoute: typeof AdminWarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$': {
      id: '/dashboard/$'
      path: '/dashboard/$'
      fullPath: '/dashboard/$'
      preLoaderRoute: typeof DashboardSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/dashboard/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/dashboard/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/dashboard/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/dashboard/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/repairs': {
      id: '/dashboard/repairs'
      path: '/dashboard/repairs'
      fullPath: '/dashboard/repairs'
      preLoaderRoute: typeof DashboardRepairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/dashboard/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/warranty': {
      id: '/dashboard/warranty'
      path: '/dashboard/warranty'
      fullPath: '/dashboard/warranty'
      preLoaderRoute: typeof DashboardWarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wishlist': {
      id: '/dashboard/wishlist'
      path: '/dashboard/wishlist'
      fullPath: '/dashboard/wishlist'
      preLoaderRoute: typeof DashboardWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repairs/': {
      id: '/repairs/'
      path: '/repairs'
      fullPath: '/repairs/'
      preLoaderRoute: typeof RepairsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory/': {
      id: '/admin/inventory/'
      path: '/admin/inventory'
      fullPath: '/admin/inventory/'
      preLoaderRoute: typeof AdminInventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory/low-stock': {
      id: '/admin/inventory/low-stock'
      path: '/admin/inventory/low-stock'
      fullPath: '/admin/inventory/low-stock'
      preLoaderRoute: typeof AdminInventoryLowStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/receipt/$id': {
      id: '/dashboard/receipt/$id'
      path: '/dashboard/receipt/$id'
      fullPath: '/dashboard/receipt/$id'
      preLoaderRoute: typeof DashboardReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  StoresRoute: StoresRoute,
  WishlistRoute: WishlistRoute,
  AdminSplatRoute: AdminSplatRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPaywayRoute: AdminPaywayRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminPurchaseOrdersRoute: AdminPurchaseOrdersRoute,
  AdminRepairsRoute: AdminRepairsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminTechniciansRoute: AdminTechniciansRoute,
  AdminWarrantyRoute: AdminWarrantyRoute,
  BlogSlugRoute: BlogSlugRoute,
  DashboardSplatRoute: DashboardSplatRoute,
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardRepairsRoute: DashboardRepairsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardWarrantyRoute: DashboardWarrantyRoute,
  DashboardWishlistRoute: DashboardWishlistRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  RepairsIndexRoute: RepairsIndexRoute,
  AdminInventoryLowStockRoute: AdminInventoryLowStockRoute,
  DashboardReceiptIdRoute: DashboardReceiptIdRoute,
  AdminInventoryIndexRoute: AdminInventoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
